name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Descarga el código del repositorio
        uses: actions/checkout@v4
      - name: Set up JDK 17 # Instala y configura Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Dar permisos a gradlew # Da permisos de ejecución al script gradlew
        run: chmod +x ./gradlew
      - name: Run tests # Ejecuta las pruebas automatizadas
        run: ./gradlew test
      - name: Build with Gradle # Compila el proyecto y genera el .jar ejecutable
        run: ./gradlew build
      - name: Publicar artefacto .jar # Publica el archivo .jar generado como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
